server.port=8080
server.servlet.session.timeout=60m

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.yzfbpzvrsuyndlwnpouh
spring.datasource.password=mUqas6sZtsGzjfdK
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

spring.security.user.name=admin
spring.security.user.password=admin

spotify.client-id=1fd7325d8d3346639063f1d0136de875
spotify.client-secret=a014eaf48d8e450d8c9d814925a33200

supabase.url=https://yzfbpzvrsuyndlwnpouh.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6ZmJwenZyc3V5bmRsd25wb3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyOTgzMTEsImV4cCI6MjA4ODg3NDMxMX0.zNHekQpbjeRXitDsJrbsY7VANUkPn8bE6k2Sh-GSil8

spring.application.name=Music Library

spring.cache.type=simple

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ulkior51020@gmail.com
spring.mail.password=rrdlnwddlidphbdz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
